version: '2.1'

networks:
  metrics:

services:
  db:
    image: 'postgres:16'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=twilio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: 'redis:7.0.10-alpine'
    container_name: redis
    ports:
      - '6379:6379'